Get All SFO API added - Scottish-Natural-Heritage/Licensing#716
Scottish-Natural-Heritage/standard-forestry-operations-api pull request #18
Opened 2021-06-24 12:57 UTC by jmassie

Added Get All SFO API #716

2021-06-25 11:03 UTC, MikeCoats commented
@jmassie The reason for this first failure...

```
 1.  AssertionError  JSON response length is greater than 1                
                     expected 0 to be above 1                              
                     at assertion:1 in test-script                         
                     inside "Get All Standard Forestry Operations"    
```

...is that your get all call happens before any inserts. You've got a test that says you should return at least two items, but if you start with an empty database (like CI/CD on GA does) then you'll get 0 items in response. You need to add something like...

```js
const port = pm.collectionVariables.get("SFO_API_PORT");
const path = pm.collectionVariables.get("SFO_API_PATH_PREFIX");

for (let i = 0; i < 3; i++) {
  pm.sendRequest({
    url:`http://localhost:${port}/${path}/v1/applications`,
    method:'POST'
  });
}
```

...to the `Pre-req.` tab on your `Get All Standard Forestry Operations` request to make sure that it inserts some rows before it searches for them.

The reason for the second and third failures...

```
2.  AssertionError  Status code is 200 OK                                 
                     expected response to have status code 200 but got 500 
                     at assertion:0 in test-script                         
                     inside "Update an Application"                        
                                                                           
 3.  AssertionError  Returned object matches posted object                 
                     expected false to deeply equal undefined              
                     at assertion:1 in test-script                         
                     inside "Update an Application"         
```

...are because GAs triggered from a PR don't get given any secrets, so it doesn't pass in a `SFO_NOTIFY_API_KEY` and the `PUT` test fails. If you take a look at [this part of my latest TR-API PR](https://github.com/Scottish-Natural-Heritage/trap-registration-api/pull/34/commits/023e289a75e67193f524cedb77fe877dcdb7a948#diff-d7f41ba1aa74f41ef4b0c2337abe593d08092ffae6528a8aa2db712afeee0b66L297-R306) You can see how I've 'hacked' around that.

2021-06-25 12:02 UTC, MikeCoats requested changes
The main thing here is to include the Setts when you return the Applications. That will let you search for GridRefs in the front-end.

2021-07-01 08:43 UTC, jmassie commented on src/controllers/application.js
> +    return Application.findAll();
Resolved

2021-07-02 10:02 UTC, MikeCoats commented on src/controllers/application.js
> +    return Application.findAll();
Resolved in 13e1fc9e3c9f5b9d46f39d2bfe5fe27de3a25d8a.

2021-07-02 10:13 UTC, MikeCoats commented on package-lock.json
>            "resolved": "https://registry.npmjs.org/uuid/-/uuid-3.3.2.tgz",
Resolved in 92225a06eee7a0caa9f6239da15915522538e723.

2021-07-02 10:15 UTC, MikeCoats commented on tests/standard-forestry-operations-api.postman_collection.json
> +			"name": "Get All Standard Forestry Operations",
Resolved in 4d026663425f09aeea9a6748030cb3759ea74922.

2021-07-02 10:15 UTC, MikeCoats approved these changes
This looks good and passes all tests on my local PC.

2021-07-02 10:15 UTC, merged