Feature/add read only user to database
Scottish-Natural-Heritage/standard-forestry-operations-api pull request #40
Opened 2021-08-24 14:26 UTC by paulcoxsnh

2021-08-24 16:15 UTC, JohnJAMoore requested changes
Just one little thing

2021-08-24 16:15 UTC, JohnJAMoore commented on src/config/database.js
> +      schema: 'traps',
should this not be sfo?

2021-08-25 06:43 UTC, paulcoxsnh commented on src/config/database.js
> +      schema: 'traps',
Totally - nice spot.

2021-08-25 08:51 UTC, JohnJAMoore approved these changes
LGTM 👍

2021-08-25 08:52 UTC, merged